cashflow/urls.py
from django.conf.urls import url

from . import views

app_name = 'cashflow'
urlpatterns = [
    url(r'^$', views.transaction_list, name='transaction_list'),
    url(r'^new/$', views.transaction_new, name='transaction_new'),
    url(r'^(?P<pk>\d+)/edit/$', views.transaction_edit, name='transaction_edit'),
    url(r'^(?P<pk>\d+)/pay/$', views.transaction_pay, name='transaction_pay'),
    url(r'^(?P<pk>\d+)/remove/$', views.transaction_remove, name='transaction_remove'),
    url(r'^persons/$', views.person_list, name='person_list'),
    url(r'^persons/import/$', views.person_import, name='person_import'),
    url(r'^persons/new/$', views.person_new, name='person_new'),
    url(r'^persons/(?P<pk>\d+)/edit/$', views.person_edit, name='person_edit'),
    url(r'^persons/(?P<pk>\d+)/remove/$', views.person_remove, name='person_remove'),
    url(r'^items/$', views.item_list, name='item_list'),
    url(r'^items/import/$', views.item_import, name='item_import'),
    url(r'^items/(?P<pk>\d+)/value/$', views.item_get_value, name='item_get_value'),
    url(r'^items/(?P<pk>\d+)/inventory/$', views.item_inventory_add, name='item_inventory_add'),
    url(r'^items/(?P<pk>\d+)/edit/$', views.item_edit, name='item_edit'),
    url(r'^items/(?P<pk>\d+)/remove/$', views.item_remove, name='item_remove'),
    url(r'^categories/(?P<pk>\d+)/items/$', views.category_items, name='category_items'),
    url(r'^reports/$', views.transaction_report, name='transaction_report'),

]

cede_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('cashflow.urls')),
]

cede_erp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('cashflow.urls')),
]

cashflow/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator

TransactionType = (
    (1, 'AccountReceivable'),
    (2, 'AccountPayable'),
    (3, 'InventoryInput'),
    (4, 'InventoryOutput'),
    (5, 'Loan'),
    (6, 'Devolution'),
)

class Transaction(models.Model):
	def __str__(self):
		return self.item.name + ' (' + str(self.amount) + ') '
	def was_paid(self):
		return self.paid_at is not None
	def pay(self):
		self.paid_at = timezone.now()
	def _get_transacted_at(self):
		if self.was_paid():
			return self.paid_at
		return self.created_at
	def save(self, *args, **kwargs):
		if not self.pk:
			self.item.add_inventory(-1 * self.amount)
		super(Transaction, self).save(args, kwargs)
	transaction_type = models.IntegerField(default=1, choices=TransactionType) # 1-account receivable, 2-account payable, 3-inventory input, 4-inventory output, 5-loan, 6-devolution
	category = models.ForeignKey('Category', on_delete=models.PROTECT)
	item = models.ForeignKey('Item', on_delete=models.PROTECT)
	person = models.ForeignKey('Person', on_delete=models.PROTECT)
	method = models.ForeignKey('Method', on_delete=models.PROTECT)
	item_value = models.DecimalField(default=1.00, max_digits=6, decimal_places=2)
	amount = models.DecimalField(default=1.00, max_digits=6, decimal_places=2)
	total = models.DecimalField(default=1.00, max_digits=6, decimal_places=2)
	comments = models.TextField(blank=True)
	paid_at = models.DateField(null=True, blank=True)
	created_at = models.DateTimeField(auto_now_add=True) # set when it's created
	updated_at = models.DateTimeField(auto_now=True) # set every time it's updated
	transacted_at = property(_get_transacted_at)
	is_deleted = models.BooleanField(default=False)
	class Meta:
		ordering = ["-updated_at"]

class Method(models.Model):
	def __str__(self):
		return self.name
	name = models.CharField(max_length=200, unique=True)
	created_at = models.DateTimeField(auto_now_add=True) # set when it's created
	updated_at = models.DateTimeField(auto_now=True) # set every time it's updated
	class Meta:
		ordering = ["name"]

class Item(models.Model):
	def __str__(self):
		return self.name
	def add_inventory(self, amount):
		self.inventory += amount
		if self.inventory < 0:
			self.inventory = 0
		self.save()
	name = models.CharField(max_length=200, unique=True)
	category = models.ForeignKey('Category', on_delete=models.PROTECT)
	cost_center = models.ForeignKey('CostCenter', on_delete=models.PROTECT)
	value = models.DecimalField(default=1.00, max_digits=6, decimal_places=2)
	inventory = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True) # set when it's created
	updated_at = models.DateTimeField(auto_now=True) # set every time it's updated
	class Meta:
		ordering = ["name"]

class CostCenter(models.Model):
	def __str__(self):
		return self.name
	name = models.CharField(max_length=200, unique=True)
	class Meta:
		ordering = ["name"]

class Category(models.Model):
	def __str__(self):
		return self.name
	name = models.CharField(max_length=200, unique=True)
	class Meta:
		ordering = ["name"]

class Person(models.Model):
	def __str__(self):
		return self.name
	name = models.CharField(max_length=200, unique=True)
	phone_number = models.CharField(max_length=20, validators=[RegexValidator(regex=r'^\(?\d{2}?\)?\d{8,10}$', message="Phone number must be entered in the format: '(11)999999999'. Up to 15 digits allowed.")], blank=True) # validators should be a list
	group = models.ForeignKey('Group', on_delete=models.PROTECT)
	created_at = models.DateTimeField(auto_now_add=True) # set when it's created
	updated_at = models.DateTimeField(auto_now=True) # set every time it's updated
	class Meta:
		ordering = ["name"]

class Group(models.Model):
	def __str__(self):
		return self.name
	name = models.CharField(max_length=200, unique=True)
	created_at = models.DateTimeField(auto_now_add=True) # set when it's created
	updated_at = models.DateTimeField(auto_now=True) # set every time it's updated
	class Meta:
		ordering = ["name"]

cashflow/forms.py
from django import forms
from .models import Transaction, Person, Group, Category, CostCenter, Item
from django.utils.translation import ugettext_lazy as _

class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        exclude = ['created_at', 'updated_at', 'transaction_type', 'is_deleted']
        labels = {
            'category': _('Categoria'),
            'item': _('Item'),
            'person': _('Frequentador'),
            'method': _('Forma de Pagamento'),
            'item_value': _('Valor Unitário'),
            'amount': _('Quantidade'),
            'total': _('Total'),
            'comments': _('Comentários'),
            'paid_at': _('Pago em'),
        }
        widgets = {
            'paid_at': forms.DateInput(format='%d/%m/%Y', attrs={'class':'date'}),
        }

class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        exclude = ['created_at', 'updated_at']
        labels = {
            'name': _('Nome'),
            'group': _('Grupo'),
            'phone_number': _('Telefone'),
        }
        widgets = {
            'phone_number': forms.TextInput(attrs={'class':'phone'}),
        }

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        exclude = ['created_at', 'updated_at']
        labels = {
            'name': _('Nome'),
            'category': _('Categoria'),
            'cost_center': _('Centro de Custo'),
            'value': _('Valor'),
            'inventory': _('Estoque'),
        }

class PersonImportForm(forms.Form):
    group = forms.ModelChoiceField(queryset=Group.objects.order_by('name'), empty_label="---------", label='Grupo')
    person_list = forms.CharField(label='Frequentadores', widget=forms.Textarea, help_text='1 nome por linha')

class ItemImportForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.order_by('name'), empty_label="---------", label='Categoria')
    cost_center = forms.ModelChoiceField(queryset=CostCenter.objects.order_by('name'), empty_label="---------", label='Centro de Custo')
    item_list = forms.CharField(label='Itens', widget=forms.Textarea, help_text='1 nome por linha')

class TransactionReportFilterForm(forms.Form):
    date_range = forms.CharField(label='Data')

class TransactionListFilterForm(forms.Form):
    person = forms.ModelChoiceField(queryset=Person.objects.order_by('name'), empty_label="Todos", label='Frequentador', required=False)
    item = forms.ModelChoiceField(queryset=Item.objects.order_by('name'), empty_label="Todos", label='Item', required=False)
    status = forms.ChoiceField(choices=(('all', 'Todos'),('paid','Pago'),('unpaid','Não Pago')))

class ItemListFilterForm(forms.Form):
    item = forms.ModelChoiceField(queryset=Item.objects.order_by('name'), empty_label="Todos", label='Item', required=False)
    cost_center = forms.ModelChoiceField(queryset=CostCenter.objects.order_by('name'), empty_label="Todos", label='Centro de Custo', required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.order_by('name'), empty_label="Todas", label='Categoria', required=False)

class PersonListFilterForm(forms.Form):
    person = forms.ModelChoiceField(queryset=Person.objects.order_by('name'), empty_label="Todos", label='Frequentador', required=False)
    group = forms.ModelChoiceField(queryset=Group.objects.order_by('name'), empty_label="Todos", label='Grupo', required=False)

cashflow/templates/cashflow/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}CEDE - ERP - Fluxo de Caixa{% endblock %}</title>

	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.css' %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-compass"></i> <span>CEDE - ERP</span></a>
            </div>

            <div class="clearfix"></div>

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">

                  <li><a><i class="fa fa-exchange"></i> Transações <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'cashflow:transaction_list' %}">Listar</a></li>
                      <li><a href="{% url 'cashflow:transaction_new' %}">Adicionar</a></li>
                      <li><a href="{% url 'cashflow:transaction_report' %}">Relatórios</a></li>
                    </ul>
                  </li>

				  <li><a><i class="fa fa-users"></i> Frequentadores <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'cashflow:person_list' %}">Listar</a></li>
                      <li><a href="{% url 'cashflow:person_new' %}">Adicionar</a></li>
                      <li><a href="{% url 'cashflow:person_import' %}">Importar</a></li>
                    </ul>
                  </li>

				  <li><a><i class="fa fa-list"></i> Itens <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{% url 'cashflow:item_list' %}">Listar</a></li>
                      <li><a href="{% url 'cashflow:item_import' %}">Importar</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>


            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>{% block header %}Fluxo de Caixa{% endblock %}</h3>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
			{% block content %}
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Plain Page</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                      Add content to the page ...
                  </div>
                </div>
              </div>
  		    {% endblock %}
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
	<!-- Moment -->
	<script src="{% static 'vendor/moment/moment.min.js' %}"></script>
	<!-- DatePicker -->
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
	<script src="{% static 'vendor/datepicker/js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'vendor/datepicker/locales/bootstrap-datepicker.pt-BR.min.js' %}"></script>
	<!-- Selectize -->
	<script src="{% static 'vendor/selectize/js/standalone/selectize.min.js' %}"></script>
    <!-- Custom Theme Scripts -->
    <script src="{% static 'build/js/custom.js' %}"></script>

	<!-- <script>
		$('select').selectize();
		$('button[type="reset"]').click(function(){
			window.location = window.location;
		});
		$('form').submit(function(){
			$('.save').prop('disabled', true);
		});
	</script> -->

	{% block script %}
	{% endblock %}
  </body>
</html>

cashflow/templates/cashflow/form_snippet.html
{% load widget_tweaks %}
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field|add_class:"form-control" }}
        {% if field.help_text %}
        <p class="help-block">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}

cashflow/templates/cashflow/item_list.html
{% extends 'cashflow/base.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Itens</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Filtros
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="row">
					<form method="POST" class="post-form">{% csrf_token %}
						{% include "cashflow/form_filter_snippet.html" %}
						<div class="col-lg-12">
							<button type="submit" class="btn btn-default">Filtrar</button>
							<a href="?reset=true" class="btn btn-default">Limpar</a>
						</div>
					</form>
				</div>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				Lista
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				{% if object_list %}
				<table class="table table-striped">
					<thead>
						<tr>
							<th> Nome </th>
							<th> Centro de Custo </th>
							<th> Categoria </th>
							<th> Valor </th>
							<th> Estoque </th>
							<th> Ações </th>
						</tr>
					</thead>
					<tbody>
						{% for item in object_list %}
						<tr>
							<td> {{ item.name }} </td>
							<td> {{ item.cost_center.name }} </td>
							<td> {{ item.category.name }} </td>
							<td> {{ item.value }} </td>
							<td> <span id="inventory-{{ item.id }}">{{ item.inventory }}</span>
								<div class="btn-group pull-right">
									<a type="button" class="btn btn-outline btn-primary btn-xs increase-inventory" href="{% url 'cashflow:item_inventory_add' pk=item.pk %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
									<a type="button" class="btn btn-outline btn-primary btn-xs decrease-inventory" href="{% url 'cashflow:item_inventory_add' pk=item.pk %}"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></a>
								</div>
							</td>
							<td class="text-center">
								<div class="btn-group">
									<a type="button" class="btn btn-outline btn-primary btn-xs" href="{% url 'cashflow:item_edit' pk=item.pk %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
									<a type="button" class="btn btn-outline btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'cashflow:item_edit' pk=item.pk %}">Editar</a></li>
										<li role="separator" class="divider"></li>
										<li><a href="{% url 'cashflow:item_remove' pk=item.pk %}">Excluir</a></li>
									</ul>
								</div>

							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% include "cashflow/pagination_snippet.html" %}
				{% else %}
				<p>Não há itens disponíveis.</p>
				{% endif %}
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
{% endblock %}

{% block script %}
<script>

function add_inventory(url, amount) {
	data = {
		amount: amount
	}
	$.post(url, data, function(response) {
		$('#inventory-' + response.id).text(response.inventory);
	}, 'json');
}

function increase_inventory(e) {
	e.preventDefault();
	add_inventory($(this).attr('href'), 1);
}

function decrease_inventory(e) {
	e.preventDefault();
	add_inventory($(this).attr('href'), -1);
}

$(".increase-inventory").click(increase_inventory);
$(".decrease-inventory").click(decrease_inventory);

</script>
{% endblock %}

cashflow/templates/cashflow/person_list.html
{% extends 'cashflow/base.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Frequentadores</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Filtros
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="row">
					<form method="POST" class="post-form">{% csrf_token %}
						{% include "cashflow/form_filter_snippet.html" %}
						<div class="col-lg-12">
							<button type="submit" class="btn btn-default">Filtrar</button>
							<a href="?reset=true" class="btn btn-default">Limpar</a>
						</div>
					</form>
				</div>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				Lista
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				{% if object_list %}
				<table class="table table-striped">
					<thead>
						<tr>
							<th> Nome </th>
							<th> Grupo </th>
							<th> Telefone </th>
							<th> Ações </th>
						</tr>
					</thead>
					<tbody>
						{% for person in object_list %}
						<tr>
							<td> {{ person.name }} </td>
							<td> {{ person.group.name }} </td>
							<td> {{ person.phone_number }} </td>
							<td class="text-center">
								<div class="btn-group">
									<a type="button" class="btn btn-outline btn-primary btn-xs" href="{% url 'cashflow:person_edit' pk=person.pk %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
									<a type="button" class="btn btn-outline btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'cashflow:person_edit' pk=person.pk %}">Editar</a></li>
										<li role="separator" class="divider"></li>
										<li><a href="{% url 'cashflow:person_remove' pk=person.pk %}">Excluir</a></li>
									</ul>
								</div>

							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% include "cashflow/pagination_snippet.html" %}
				{% else %}
				<p>Não há frequentadores disponíveis.</p>
				{% endif %}
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
{% endblock %}

cashflow/templates/cashflow/transaction_edit.html
{% extends 'cashflow/base.html' %}

{% block content %}
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Transações</h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Adicionar / Editar
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<form method="POST" class="post-form">{% csrf_token %}
					{% include "cashflow/form_snippet.html" %}
					<button type="submit" class="save btn btn-default">Salvar</button>
				</form>
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

{% endblock %}

{% block script %}
<script>

function update_item_value() {
	var id_item = $('#id_item').val();
	var url = "{% url 'cashflow:item_get_value' pk=0 %}".replace("0", id_item);
	$.getJSON(url, function (response) {
			if (response.value) {
				$("#id_item_value").val( response.value );
				update_total();
			}
		});
}

function update_total() {
	$("#id_total").val( parseFloat( $("#id_item_value").val() * $("#id_amount").val() ).toFixed(2) );
}

function filter_items_by_category() {
	var id_category = $(this).val();
	var url = "{% url 'cashflow:category_items' pk=0 %}".replace("0", id_category);
	$('#id_item').selectize()[0].selectize.destroy();
	$("#id_item")
		.find('option')
		.remove()
		.end()
		.append('<option value>---------</option>');
	$.getJSON(url, function(response) {
		var options = $("#id_item");
		$.each(response.items, function(i, item) {
			options.append($("<option />").val(item.id).text(item.name));
		});
		$('#id_item').selectize();
	});
}

$("#id_category").change(filter_items_by_category);
$("#id_amount").keyup(update_total);
$("#id_item_value").keyup(update_total);
$("#id_item").change(update_item_value);

$('.date').datepicker({
    todayBtn: "linked",
    clearBtn: true,
    language: "pt-BR",
    autoclose: true,
    todayHighlight: true
});

</script>
{% endblock %}

cashflow/templates/cashflow/transaction_list.html
{% extends 'cashflow/base.html' %}

{% block header %}Transações{% endblock %}

{% block content %}

{% include "cashflow/form_filter_snippet.html" %}


<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
	<div class="x_title">
	  <h2>Lista</h2>
	  <ul class="nav navbar-right panel_toolbox">
		<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
		</li>
	  </ul>
	  <div class="clearfix"></div>
	</div>
	<div class="x_content">
		{% if object_list %}
		<table width="100%" class="table table-striped table-hover">
			<thead>
				<tr>
					<th> Frequentador </th>
					<th> Grupo </th>
					<th> Item </th>
					<th> Qtd. </th>
					<th> Total </th>
					<th> Data </th>
					<th> Forma </th>
					<th> Status </th>
					<th> Ações </th>
				</tr>
			</thead>
			<tbody>
				{% for transaction in object_list %}
				<tr>
					<td> {{ transaction.person.name }} </td>
					<td> {{ transaction.person.group.name }} </td>
					<td> {{ transaction.item.name }} </td>
					<td class="text-right"> {{ transaction.amount }} </td>
					<td class="text-right"> {{ transaction.total }} </td>
					<td> {{ transaction.transacted_at|date:"d/m/y" }} </td>
					<td> {{ transaction.method.name }} </td>
					<td>
						{% if transaction.was_paid %}
						<span class="label label-success">Pago</span>
						{% else %}
						<span class="label label-warning">Não Pago</span>
						{% endif %}
					</td>
					<td class="text-center">
						<div class="btn-group">
							<a type="button" class="btn btn-outline btn-primary btn-xs" href="{% url 'cashflow:transaction_edit' pk=transaction.pk %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
							<a type="button" class="btn btn-outline btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'cashflow:transaction_edit' pk=transaction.pk %}">Editar</a></li>
								{% if transaction.was_paid == False %}
								<li><a href="{% url 'cashflow:transaction_pay' pk=transaction.pk %}">Marcar como Pago</a></li>
								{% endif %}
								<li role="separator" class="divider"></li>
								<li><a href="{% url 'cashflow:transaction_remove' pk=transaction.pk %}">Excluir</a></li>
							</ul>
						</div>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% include "cashflow/pagination_snippet.html" %}
		{% else %}
		<p>Não há transações disponíveis.</p>
		{% endif %}
	</div>
  </div>
</div>
{% endblock %}